pipeline:
  agent:
    label: 'ubuntu'
  stages:
    - stage: 'Build'
      steps:
        - script: |
            echo "Building Project"
            # Put your build commands here
            echo $PWD
    - stage: 'Test'
      steps:
        - script: |
            echo "Running Tests"
            # Put your test commands here
            echo $USER
    - stage: 'Deploy'
      steps:
        - script: |
            echo "Deploying Application"
            # Put your deploy commands here
            echo $PWD
