FROM debian:stable-slim AS base-image

RUN apt-get update &&\
    apt install -y gettext &&\
    apt install -y python3 &&\
    apt install -y python3.11-venv &&\
    apt install gettext -y &&\
    apt install pip -y

# docker build -fDockerfile-staticwebsite -t schd1337/baseimages:staticwebsite .
# docker push schd1337/baseimages:staticwebsite