apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-db
  namespace: portfoliodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfoliodb
  
  template:
    metadata:
      labels:
        app: portfoliodb

    spec:
      containers:
      - name: crow-app
        image: schd1337/portfoliodb:v1
        ports:
        - containerPort: 3306
---
# service for this db
apiVersion: v1
kind: Service
metadata:
  name: portfoliodb-expose
  namespace: portfoliodb
spec:
  type: ClusterIP 
  selector:
    app: portfolio-db
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 8001
    # Port to forward to inside the pod
    targetPort: 3306