apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolioapp   # If the Ingress is in the default namespace, it won’t find your service in portfolioapp unless fully qualified (portfolio-expose.portfolioapp.svc.cluster.local)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: portfolio-expose
              port:
                number: 8000
#        - path: /
#          pathType: Prefix
#          backend:
#            service:
#              name: portfolio-expose
#              port:
#                number: 8000