apiVersion: apps/v1
kind: Deployment
metadata:
  name: solo-leveling
  namespace: sololeveling
spec:
  replicas: 1
  selector:
    matchLabels:
      project: sololeveling
  
  template:
    metadata:
      labels:
        project: sololeveling

    spec:
      containers:
      - name: crow-app
        image: schd1337/portfolioapp:latest
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: solo-leveling-env
---

# service for this app
apiVersion: v1
kind: Service
metadata:
  name: solo-leveling-service
  namespace: sololeveling
spec:
  type: ClusterIP
  selector:
    project: sololeveling
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 8000
    # Port inside the container
    targetPort: 80

---
# Environment variables
apiVersion: v1
kind: Secret
metadata:
  name: solo-leveling-env
  namespace: sololeveling
type: Opaque
data:
  ################## DATABASE ########################
  HOSTNAME: dGNwOi8vU29sby1MZXZlbGluZy1kYi1zZXJ2aWNlOjMzMDYvVXNlcnM=
  USERNAME: cm9vdA==
  SCHEMA: VXNlcnM=
  PASSWORD: U2VjdXJl
  PORT: MzMwNg==
  ############## CROWCPP #####################
  HTTP_PORT: ODA=
  THREADS: Mg==
  #################### HTML VAriables ####################
  HTML_IP: MTkyLjE2OC4wLjIw
  HTML_PORT: ODA=