name: CI/CD for my personal website

on: push

jobs:
  compile-build_image-push:
    if: github.ref == 'refs/heads/website'

    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v3

    - name: Create a docker image of the application
      run: docker build -t schd1337/mywebsite:latest .
      shell: bash

    - name: Push Docker image into the dockerhub
      run: |
            echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker push schd1337/mywebsite:latest
      shell: bash