name: CI/CD for my project

on: push

jobs:
  compile-build_image-push:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v3

    - name: Using utility container to compile the code
      run: docker run --rm -v $PWD:/build-app:rw schd1337/portfolioapp:compiler
      shell: bash

    - name: Create a docker image of the application
      run: docker build -t schd1337/portfolioapp:latest .
      shell: bash

    - name: Push Docker image into the dockerhub
      run: |
            echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker push schd1337/portfolioapp:latest
      shell: bash

  ssh-deploy-project-Solo:
    needs: compile-build_image-push
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and deploy
      run: |
            echo "${{ secrets.EC2_KEY }}" | tee $PWD/ec2.pem
            chmod 600 $PWD/ec2.pem
            ssh -o "StrictHostKeyChecking=no" -i "ec2.pem" admin@ec2-43-205-241-114.ap-south-1.compute.amazonaws.com "git clone https://github.com/AstroKabutar/SoloLeveling.git"
            ssh -o "StrictHostKeyChecking=no" -i "ec2.pem" admin@ec2-43-205-241-114.ap-south-1.compute.amazonaws.com "kubectl apply -f SoloLeveling/kubernetes/dbdeploy.yaml"
            ssh -o "StrictHostKeyChecking=no" -i "ec2.pem" admin@ec2-43-205-241-114.ap-south-1.compute.amazonaws.com "kubectl apply -f SoloLeveling/kubernetes/project-upskill.yaml"
            ssh -o "StrictHostKeyChecking=no" -i "ec2.pem" admin@ec2-43-205-241-114.ap-south-1.compute.amazonaws.com "rm -rf SoloLeveling"
      shell: bash            